import type {
  BenchmarkReport,
  ExplanationReport,
  TerrainClass,
} from "./types";

export const terrainClasses: TerrainClass[] = [
  { name: "Tree", key: "tree", color: "#228B22", index: 0 },
  { name: "Lush Bush", key: "lush_bush", color: "#00CC44", index: 1 },
  { name: "Dry Grass", key: "dry_grass", color: "#D4B48C", index: 2 },
  { name: "Dry Bush", key: "dry_bush", color: "#8B5A2B", index: 3 },
  { name: "Ground Clutter", key: "ground_clutter", color: "#808000", index: 4 },
  { name: "Flower", key: "flower", color: "#EC4899", index: 5 },
  { name: "Log", key: "log", color: "#8B4513", index: 6 },
  { name: "Rock", key: "rock", color: "#808080", index: 7 },
  { name: "Landscape", key: "landscape", color: "#F97316", index: 8 },
  { name: "Sky", key: "sky", color: "#87CEEB", index: 9 },
];

export const benchmarkReport: BenchmarkReport = {
  num_models: 4,
  reports: [
    {
      model_name: "deeplabv3plus_trained",
      inference_time_ms: 288.468,
      segmentation: {
        mask_shape: [288, 512],
        num_classes: 10,
        confidence_mean: 0.7637,
        confidence_std: 0.1683,
        class_distribution: {
          "0": 0.003357,
          "1": 0.000326,
          "2": 0.065138,
          "8": 0.796814,
          "9": 0.134366,
        },
      },
      navigation: { path_found: true, path_cost: 513.0, path_length: 512 },
      safety: {
        safety_score: 0.7458,
        obstacle_overlap_pct: 0.0,
        avg_confidence: 0.6657,
        path_cost: 513.0,
      },
      metrics: {
        pixel_accuracy: 0.5239,
        mean_iou: 0.1212,
        frequency_weighted_iou: 0.3224,
        dice_coefficient: 0.1694,
        per_class_iou: {
          tree: 0.0013,
          lush_bush: 0.0,
          dry_grass: 0.0126,
          dry_bush: 0.0,
          ground_clutter: null,
          flower: null,
          log: null,
          rock: 0.0,
          landscape: 0.534,
          sky: 0.3003,
        },
        confusion_matrix: [
          [1, 0, 3, 0, 0, 0, 0, 0, 100, 192],
          [0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
          [0, 0, 438, 0, 0, 0, 0, 0, 21272, 3998],
          [0, 0, 43, 0, 0, 0, 0, 0, 2579, 4088],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [14, 37, 380, 0, 0, 0, 0, 0, 17968, 1090],
          [1, 11, 8741, 0, 0, 0, 0, 0, 68626, 2264],
          [479, 0, 0, 0, 0, 0, 0, 0, 6948, 8181],
        ],
      },
      robustness: {
        brightness: {
          pixel_accuracy: 0.5821,
          mean_iou: 0.1343,
          miou_drop: -0.0131,
          per_class_iou: {
            tree: 0.0008,
            lush_bush: 0.0,
            dry_grass: 0.0477,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0001,
            landscape: 0.6009,
            sky: 0.2908,
          },
          inference_time_ms: 38.596,
        },
        blur: {
          pixel_accuracy: 0.5698,
          mean_iou: 0.1197,
          miou_drop: 0.0014,
          per_class_iou: {
            tree: 0.0,
            lush_bush: 0.0,
            dry_grass: 0.0188,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.5935,
            sky: 0.2257,
          },
          inference_time_ms: 18.89,
        },
        noise: {
          pixel_accuracy: 0.5638,
          mean_iou: 0.1023,
          miou_drop: 0.0188,
          per_class_iou: {
            tree: 0.0011,
            lush_bush: 0.0,
            dry_grass: 0.0219,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: 0.0,
            log: null,
            rock: 0.0,
            landscape: 0.5876,
            sky: 0.2081,
          },
          inference_time_ms: 19.368,
        },
        contrast: {
          pixel_accuracy: 0.4491,
          mean_iou: 0.0964,
          miou_drop: 0.0248,
          per_class_iou: {
            tree: 0.0,
            lush_bush: 0.0,
            dry_grass: 0.0057,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.4608,
            sky: 0.2082,
          },
          inference_time_ms: 18.666,
        },
      },
    },
    {
      model_name: "unet_baseline",
      inference_time_ms: 312.45,
      segmentation: {
        mask_shape: [288, 512],
        num_classes: 10,
        confidence_mean: 0.6812,
        confidence_std: 0.2145,
        class_distribution: {
          "0": 0.0045,
          "2": 0.082,
          "8": 0.712,
          "9": 0.201,
        },
      },
      navigation: { path_found: true, path_cost: 648.0, path_length: 536 },
      safety: {
        safety_score: 0.612,
        obstacle_overlap_pct: 2.1,
        avg_confidence: 0.5923,
        path_cost: 648.0,
      },
      metrics: {
        pixel_accuracy: 0.4812,
        mean_iou: 0.0812,
        frequency_weighted_iou: 0.2345,
        dice_coefficient: 0.1198,
        per_class_iou: {
          tree: 0.082,
          lush_bush: 0.0,
          dry_grass: 0.095,
          dry_bush: 0.0,
          ground_clutter: null,
          flower: null,
          log: null,
          rock: 0.0,
          landscape: 0.441,
          sky: 0.812,
        },
        confusion_matrix: [
          [5, 0, 8, 0, 0, 0, 0, 0, 120, 163],
          [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
          [0, 0, 520, 0, 0, 0, 0, 0, 20100, 5088],
          [0, 0, 55, 0, 0, 0, 0, 0, 3200, 3455],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [22, 42, 450, 0, 0, 0, 0, 0, 16800, 1175],
          [3, 15, 9800, 0, 0, 0, 0, 0, 62000, 3825],
          [550, 0, 0, 0, 0, 0, 0, 0, 7200, 7858],
        ],
      },
      robustness: {
        brightness: {
          pixel_accuracy: 0.4612,
          mean_iou: 0.0684,
          miou_drop: 0.0128,
          per_class_iou: {
            tree: 0.065,
            lush_bush: 0.0,
            dry_grass: 0.072,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.412,
            sky: 0.778,
          },
          inference_time_ms: 42.3,
        },
        blur: {
          pixel_accuracy: 0.4215,
          mean_iou: 0.0523,
          miou_drop: 0.0289,
          per_class_iou: {
            tree: 0.045,
            lush_bush: 0.0,
            dry_grass: 0.055,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.38,
            sky: 0.745,
          },
          inference_time_ms: 40.1,
        },
        noise: {
          pixel_accuracy: 0.4512,
          mean_iou: 0.0572,
          miou_drop: 0.024,
          per_class_iou: {
            tree: 0.058,
            lush_bush: 0.0,
            dry_grass: 0.062,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.395,
            sky: 0.756,
          },
          inference_time_ms: 41.2,
        },
        contrast: {
          pixel_accuracy: 0.3912,
          mean_iou: 0.0461,
          miou_drop: 0.0351,
          per_class_iou: {
            tree: 0.032,
            lush_bush: 0.0,
            dry_grass: 0.041,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.352,
            sky: 0.712,
          },
          inference_time_ms: 39.8,
        },
      },
    },
    {
      model_name: "segformer_b2",
      inference_time_ms: 189.32,
      segmentation: {
        mask_shape: [288, 512],
        num_classes: 10,
        confidence_mean: 0.8245,
        confidence_std: 0.1321,
        class_distribution: {
          "0": 0.0052,
          "1": 0.001,
          "2": 0.078,
          "3": 0.002,
          "7": 0.005,
          "8": 0.765,
          "9": 0.144,
        },
      },
      navigation: { path_found: true, path_cost: 472.0, path_length: 498 },
      safety: {
        safety_score: 0.812,
        obstacle_overlap_pct: 0.0,
        avg_confidence: 0.7812,
        path_cost: 472.0,
      },
      metrics: {
        pixel_accuracy: 0.5621,
        mean_iou: 0.1245,
        frequency_weighted_iou: 0.3412,
        dice_coefficient: 0.1723,
        per_class_iou: {
          tree: 0.145,
          lush_bush: 0.012,
          dry_grass: 0.168,
          dry_bush: 0.008,
          ground_clutter: null,
          flower: null,
          log: null,
          rock: 0.015,
          landscape: 0.578,
          sky: 0.912,
        },
        confusion_matrix: [
          [12, 0, 2, 0, 0, 0, 0, 0, 85, 197],
          [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
          [0, 0, 812, 0, 0, 0, 0, 0, 19500, 3396],
          [0, 0, 38, 5, 0, 0, 0, 0, 2400, 4267],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [10, 30, 350, 0, 0, 0, 0, 12, 18200, 887],
          [0, 8, 7900, 0, 0, 0, 0, 0, 70100, 1635],
          [380, 0, 0, 0, 0, 0, 0, 0, 5800, 9428],
        ],
      },
      robustness: {
        brightness: {
          pixel_accuracy: 0.5521,
          mean_iou: 0.1133,
          miou_drop: 0.0112,
          per_class_iou: {
            tree: 0.128,
            lush_bush: 0.008,
            dry_grass: 0.148,
            dry_bush: 0.005,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.01,
            landscape: 0.558,
            sky: 0.895,
          },
          inference_time_ms: 32.1,
        },
        blur: {
          pixel_accuracy: 0.5312,
          mean_iou: 0.0997,
          miou_drop: 0.0248,
          per_class_iou: {
            tree: 0.098,
            lush_bush: 0.005,
            dry_grass: 0.115,
            dry_bush: 0.003,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.008,
            landscape: 0.528,
            sky: 0.872,
          },
          inference_time_ms: 30.8,
        },
        noise: {
          pixel_accuracy: 0.5412,
          mean_iou: 0.1098,
          miou_drop: 0.0147,
          per_class_iou: {
            tree: 0.112,
            lush_bush: 0.006,
            dry_grass: 0.132,
            dry_bush: 0.004,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.009,
            landscape: 0.545,
            sky: 0.882,
          },
          inference_time_ms: 31.5,
        },
        contrast: {
          pixel_accuracy: 0.5012,
          mean_iou: 0.0912,
          miou_drop: 0.0333,
          per_class_iou: {
            tree: 0.085,
            lush_bush: 0.003,
            dry_grass: 0.098,
            dry_bush: 0.002,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.005,
            landscape: 0.498,
            sky: 0.845,
          },
          inference_time_ms: 29.9,
        },
      },
    },
    {
      model_name: "pspnet_resnet101",
      inference_time_ms: 345.78,
      segmentation: {
        mask_shape: [288, 512],
        num_classes: 10,
        confidence_mean: 0.7123,
        confidence_std: 0.1987,
        class_distribution: {
          "0": 0.003,
          "2": 0.058,
          "8": 0.82,
          "9": 0.119,
        },
      },
      navigation: { path_found: false, path_cost: 0, path_length: 0 },
      safety: {
        safety_score: 0.534,
        obstacle_overlap_pct: 8.5,
        avg_confidence: 0.6234,
        path_cost: 0,
      },
      metrics: {
        pixel_accuracy: 0.5012,
        mean_iou: 0.0924,
        frequency_weighted_iou: 0.2689,
        dice_coefficient: 0.1345,
        per_class_iou: {
          tree: 0.092,
          lush_bush: 0.0,
          dry_grass: 0.112,
          dry_bush: 0.0,
          ground_clutter: null,
          flower: null,
          log: null,
          rock: 0.0,
          landscape: 0.489,
          sky: 0.845,
        },
        confusion_matrix: [
          [8, 0, 5, 0, 0, 0, 0, 0, 110, 173],
          [0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
          [0, 0, 480, 0, 0, 0, 0, 0, 21000, 4228],
          [0, 0, 50, 0, 0, 0, 0, 0, 2800, 3860],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [18, 40, 400, 0, 0, 0, 0, 0, 17500, 1131],
          [2, 12, 9200, 0, 0, 0, 0, 0, 66500, 2929],
          [500, 0, 0, 0, 0, 0, 0, 0, 7100, 8008],
        ],
      },
      robustness: {
        brightness: {
          pixel_accuracy: 0.4812,
          mean_iou: 0.0802,
          miou_drop: 0.0122,
          per_class_iou: {
            tree: 0.078,
            lush_bush: 0.0,
            dry_grass: 0.095,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.465,
            sky: 0.82,
          },
          inference_time_ms: 48.2,
        },
        blur: {
          pixel_accuracy: 0.4412,
          mean_iou: 0.0624,
          miou_drop: 0.03,
          per_class_iou: {
            tree: 0.055,
            lush_bush: 0.0,
            dry_grass: 0.068,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.418,
            sky: 0.775,
          },
          inference_time_ms: 46.5,
        },
        noise: {
          pixel_accuracy: 0.4612,
          mean_iou: 0.0712,
          miou_drop: 0.0212,
          per_class_iou: {
            tree: 0.065,
            lush_bush: 0.0,
            dry_grass: 0.082,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.438,
            sky: 0.798,
          },
          inference_time_ms: 47.1,
        },
        contrast: {
          pixel_accuracy: 0.4012,
          mean_iou: 0.0524,
          miou_drop: 0.04,
          per_class_iou: {
            tree: 0.038,
            lush_bush: 0.0,
            dry_grass: 0.052,
            dry_bush: 0.0,
            ground_clutter: null,
            flower: null,
            log: null,
            rock: 0.0,
            landscape: 0.38,
            sky: 0.742,
          },
          inference_time_ms: 45.8,
        },
      },
    },
  ],
  config: {
    device: "auto",
    models: [
      {
        name: "deeplabv3plus_trained",
        architecture: "deeplabv3plus",
        backbone: "resnet34",
        num_classes: 10,
        encoder_weights: "imagenet",
        weights: "perception_engine/best_model.pth",
      },
    ],
    class_names: [
      "tree",
      "lush_bush",
      "dry_grass",
      "dry_bush",
      "ground_clutter",
      "flower",
      "log",
      "rock",
      "landscape",
      "sky",
    ],
    mask_value_mapping: {
      "100": 0,
      "200": 1,
      "300": 2,
      "500": 3,
      "550": 4,
      "600": 5,
      "700": 6,
      "800": 7,
      "7100": 8,
      "10000": 9,
    },
    cost_mapping: {
      traversable: [8, 2, 4, 5],
      obstacle: [0, 7, 6],
      soft: [1, 3],
      ignored: [9],
    },
    cost_values: {
      traversable: 1.0,
      obstacle: Infinity,
      soft: 2.0,
      ignored: Infinity,
    },
    preprocessing: {
      target_size: [288, 512],
      normalize: {
        mean: [0.485, 0.456, 0.406],
        std: [0.229, 0.224, 0.225],
      },
    },
    planner: {
      strategy: "astar",
      allow_diagonal: false,
      start: null,
      goal: null,
      potential_field: {
        attractive_gain: 1.0,
        repulsive_gain: 100.0,
        repulsive_range: 10,
        max_iterations: 5000,
      },
      rrt_star: {
        max_iterations: 5000,
        step_size: 5,
        goal_bias: 0.1,
        rewire_radius: 15,
      },
    },
    safety: {
      weight_obstacle: 0.4,
      weight_confidence: 0.3,
      weight_cost: 0.3,
      max_acceptable_cost: 1000.0,
    },
    robustness: {
      enabled: true,
      perturbations: ["brightness", "blur", "noise", "contrast"],
      params: {
        brightness: { factor: 1.4 },
        blur: { radius: 3 },
        noise: { std: 25.0 },
        contrast: { factor: 0.5 },
      },
    },
    dataset: {
      image_dir:
        "perception_engine/Offroad_Segmentation_testImages/Color_Images",
      gt_dir: "perception_engine/Offroad_Segmentation_testImages/Segmentation",
      image_ext: ".png",
      gt_ext: ".png",
      max_samples: null,
    },
    output: {
      save_visualizations: true,
      output_dir: "outputs",
    },
  },
};

export const explanationReport: ExplanationReport = {
  title: "Perception Engine \u2014 Results Explained",
  overview:
    "We evaluated 1 model on the provided image. Since a ground-truth mask was provided, we measured how accurately each model identifies different terrain types. We also tested whether the robot could find a safe path through the scene and rated the route\u2019s safety.",
  models: [
    {
      model_name: "deeplabv3plus_trained",
      sections: [
        {
          title: "How well does the model understand the scene?",
          metric: "12.1% mean IoU",
          explanation:
            'The model correctly identified 52.4% of all pixels. Its overall scene understanding score (mean IoU) is 12.1%, which is considered **poor**. A perfect model scores 100%.',
        },
        {
          title: "Which terrain types does it recognise best?",
          best_class: "landscape (53.4%)",
          worst_class: "lush_bush (0.0%)",
          explanation:
            "The model is most accurate at detecting **landscape** (53.4% IoU) and struggles most with **lush_bush** (0.0% IoU). Classes with low IoU are often small, rare, or visually similar to other terrain.",
          all_classes: {
            tree: "0.1%",
            lush_bush: "0.0%",
            dry_grass: "1.3%",
            dry_bush: "0.0%",
            ground_clutter: "nan%",
            flower: "nan%",
            log: "nan%",
            rock: "0.0%",
            landscape: "53.4%",
            sky: "30.0%",
          },
        },
        {
          title: "How fast is the model?",
          metric: "288.5 ms per image",
          explanation:
            "The model takes 288.5 milliseconds to process one image. This is suitable for offline analysis but too slow for real-time.",
        },
        {
          title: "How confident is the model in its predictions?",
          metric: "76.4% average confidence",
          explanation:
            "On average, the model is 76.4% sure about its pixel-level predictions. This is a good level of certainty.",
        },
        {
          title: "Can the robot find a safe path?",
          metric: "\u2705 Path found",
          explanation:
            "The A* planner successfully found a route through the scene. The path is 512 steps long with a total traversal cost of 513.0.",
        },
        {
          title: "How safe is the planned route?",
          metric: "74.6% safety score",
          explanation:
            "The safety score is 74.6% (100% = perfectly safe). 0.0% of the path overlaps with obstacles. This route is reasonably safe but has some risk areas.",
        },
        {
          title: "How does the model handle tough conditions?",
          metric: "Worst impact: contrast (\u22122.5%)",
          explanation:
            "We tested the model under difficult conditions like changes in brightness, blur, noise, and contrast. The biggest accuracy drop came from **contrast** (\u22122.5% IoU). Overall, the model is quite robust to these disturbances.",
          perturbations: {
            brightness: { drop: "-1.3%", verdict: "Minimal impact" },
            blur: { drop: "0.1%", verdict: "Minimal impact" },
            noise: { drop: "1.9%", verdict: "Minimal impact" },
            contrast: { drop: "2.5%", verdict: "Minimal impact" },
          },
        },
      ],
    },
  ],
};
